stages:
  - deploy

.setup_environment: &setup_environment
  - echo "Configure databricks access"
  - export MANAGED_IDENTITY_CLIENT_ID=MANAGED_IDENTITY_CLIENT_ID_${ENV^^}
  - export MANAGED_IDENTITY_CLIENT_ID=${!MANAGED_IDENTITY_CLIENT_ID}
  - export DATABRICKS_HOST=DATABRICKS_HOST_${ENV^^}_${CLOUD_PROVIDER^^}_${REGION^^}
  - export DATABRICKS_HOST=${!DATABRICKS_HOST}
  - export DATABRICKS_GROUP=${DATABRICKS_DEVELOPERS_GROUP}-${ENV}
  - export DATABRICKS_NOTIFICATION_EMAIL=DATABRICKS_NOTIFICATION_EMAIL_${ENV^^}
  - export DATABRICKS_NOTIFICATION_EMAIL=${!DATABRICKS_NOTIFICATION_EMAIL}
  - echo "DATABRICKS_HOST is ${DATABRICKS_HOST}"
  - echo "Insert environment variables into asset bundle definition"
  - envsubst "$(compgen -e | sed -e 's/^/$/')" < databricks.yml | sponge databricks.yml
  - cat databricks.yml
  - cd $BUNDLE_PATH
  - az login --identity --username "${MANAGED_IDENTITY_CLIENT_ID}"

.validate_bundle: &validate_bundle
  - databricks bundle validate

.deploy_bundle: &deploy_bundle
  - echo "Deploy asset bundle to databricks"
  - databricks bundle deploy -t "${ENV}"

.dev_rules: &dev_rules
  - if: '$CI_COMMIT_BRANCH == "main"'
    when: on_success
  - if: $CI_COMMIT_BRANCH =~ /^feature\/.*$/
    when: manual
  - if: $CI_COMMIT_BRANCH =~ /^defect\/.*$/
    when: manual

.uat_rules: &uat_rules
  - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-rc\.\d+$/
    when: on_success
  
.prod_rules: &prod_rules
  - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
    when: manual

deploy-azr-westus:dev:
  image: $BDDM_ACR/$DATABRICKS_CLI_IMAGE
  stage: deploy
  rules:
    - *dev_rules
  variables:
    ENV: "dev"
    CLOUD_PROVIDER: "azr"
    REGION: "westus"
  script:
    - *setup_environment
    - *validate_bundle
    - *deploy_bundle
  environment:
    name: ${ENV}
    url: ${DATABRICKS_HOST}
  
deploy-azr-westus:uat:
  image: $BDDM_ACR/$DATABRICKS_CLI_IMAGE
  stage: deploy
  rules:
     - *uat_rules
  variables:
    ENV: "uat"
    CLOUD_PROVIDER: "azr"
    REGION: "westus"
    SCHEDULE: "0 0 6,12 * * ?"
  script:
    - *setup_environment
    - *validate_bundle
    - *deploy_bundle
  environment:
    name: ${ENV}
    url: ${DATABRICKS_HOST}

deploy-azr-westus:prod:
  image: $BDDM_ACR/$DATABRICKS_CLI_IMAGE
  stage: deploy
  rules:
    - *prod_rules
  variables:
   ENV: "prod"
   CLOUD_PROVIDER: "azr"
   REGION: "westus"
   SCHEDULE: "0 0 6,12 * * ?"
  script:
    - *setup_environment
    - *validate_bundle
    - *deploy_bundle
  environment:
    name: ${ENV}
    url: ${DATABRICKS_HOST}
