apiVersion: v3.0.0
kind: DataContract
id: my-data-contract-id
name: Testing Data Contract
version: 1.0.0
domain: flight
status: active
schema:
- name: customer
  physicalName: customer
  logicalType: object
  physicalType: null
  description: customer table description
  properties:
  - name: customer_id
    logicalType: integer
    physicalType: int
  - name: first_name
    logicalType: string
    physicalType: string
  - name: last_name
    logicalType: string
    physicalType: string
  - name: email
    logicalType: string
    physicalType: string
  - name: phone
    logicalType: string
    physicalType: string
  - name: address
    logicalType: string
    physicalType: string
  - name: city
    logicalType: string
    physicalType: string
  - name: state
    logicalType: string
    physicalType: string
  - name: zip_code
    logicalType: number
    physicalType: double
  - name: join_date
    logicalType: date
    physicalType: date
  quality:
  - type: sql
    description: Ensures customer has data
    query: SELECT COUNT(*) FROM customer
    mustBeGreaterThanOrEqualTo: 0
  - type: sql
    description: Ensure customer has no duplicate rows across all columns
    query: SELECT COUNT(*) FROM ( SELECT *, COUNT(*) OVER (PARTITION BY customer_id,
      first_name, last_name, email, phone, address, city, state, zip_code, join_date)
      AS row_count FROM customer ) AS subquery WHERE row_count > 1
    mustBe: 0
  - type: sql
    description: Ensures customer table has 100 or less customers
    query: SELECT COUNT(*) FROM customer
    mustBeLessThanOrEqualTo: 100
  - type: sql
    description: Ensures every customer has an email
    query: SELECT COUNT(*) FROM customer WHERE email IS NULL
    mustBe: 0
  - type: sql
    description: Ensures every customer has a first and last name
    query: SELECT COUNT(*) FROM customer WHERE first_name IS NULL OR last_name IS
      NULL
    mustBe: 0
- name: customer2
  physicalName: customer2
  logicalType: object
  physicalType: null
  description: customer2 table description
  properties:
  - name: customer_id
    logicalType: integer
    physicalType: int
  - name: first_name
    logicalType: string
    physicalType: string
  - name: last_name
    logicalType: string
    physicalType: string
  - name: email
    logicalType: string
    physicalType: string
  - name: phone
    logicalType: string
    physicalType: string
  - name: address
    logicalType: string
    physicalType: string
  - name: city
    logicalType: string
    physicalType: string
  - name: state
    logicalType: string
    physicalType: string
  - name: zip_code
    logicalType: number
    physicalType: double
  - name: join_date
    logicalType: date
    physicalType: date
  quality:
  - type: sql
    description: Ensures customer2 has data
    query: SELECT COUNT(*) FROM customer2
    mustBeGreaterThanOrEqualTo: 0
  - type: sql
    description: Ensure customer2 has no duplicate rows across all columns
    query: SELECT COUNT(*) FROM ( SELECT *, COUNT(*) OVER (PARTITION BY customer_id,
      first_name, last_name, email, phone, address, city, state, zip_code, join_date)
      AS row_count FROM customer2 ) AS subquery WHERE row_count > 1
    mustBe: 0
- name: my_managed_table1
  physicalName: my_managed_table1
  logicalType: object
  physicalType: null
  description: my_managed_table1 description
  properties:
  - name: id
    logicalType: integer
    physicalType: int
  - name: name
    logicalType: string
    physicalType: string
  - name: age
    logicalType: integer
    physicalType: int
  - name: city
    logicalType: string
    physicalType: string
  quality:
  - type: sql
    description: Ensures my_managed_table1 has data
    query: SELECT COUNT(*) FROM my_managed_table1
    mustBeGreaterThanOrEqualTo: 0
  - type: sql
    description: Ensure my_managed_table1 has no duplicate rows across all columns
    query: SELECT COUNT(*) FROM ( SELECT *, COUNT(*) OVER (PARTITION BY id, name,
      age, city) AS row_count FROM my_managed_table1 ) AS subquery WHERE row_count
      > 1
    mustBe: 0
- name: my_managed_table2
  physicalName: my_managed_table2
  logicalType: object
  physicalType: null
  description: my_managed_table2 description
  properties:
  - name: id
    logicalType: integer
    physicalType: int
  - name: name
    logicalType: string
    physicalType: string
  - name: age
    logicalType: integer
    physicalType: int
  - name: city
    logicalType: string
    physicalType: string
  quality:
  - type: sql
    description: Ensures my_managed_table2 has data
    query: SELECT COUNT(*) FROM my_managed_table2
    mustBeGreaterThanOrEqualTo: 0
  - type: sql
    description: Ensure my_managed_table2 has no duplicate rows across all columns
    query: SELECT COUNT(*) FROM ( SELECT *, COUNT(*) OVER (PARTITION BY id, name,
      age, city) AS row_count FROM my_managed_table2 ) AS subquery WHERE row_count
      > 1
    mustBe: 0
dataProduct: flight data products
tenant: boeing airlines
description:
  purpose: Tables with test data for testing
  limitations: null
  usage: null
tags:
- flight
- das
servers:
- server: development
  type: databricks
  host: adb-5809742986594827.7.azuredatabricks.net
  catalog: hive_metastore
  schema: default
support:
- channel: DAS Teams Channel
  tool: teams
  scope: interactive
  url: https://teams.microsoft.com/channel/das
- channel: DAS Teams Channel
  tool: teams
  scope: announcements
  url: https://teams.microsoft.com/channel/das/announcements
- channel: DAS Email
  tool: email
  scope: announcements
  url: mailto:dasteam@boeing.com
  description:
  - Team email for all team announcements
