name: Deploy Databricks Contracts Workflows

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ENVIRONMENT: # variable
        description: 'Deploy Environment (dev/test/prod)'
        required: true
        default: 'dev'
      USER_EMAIL: # variable
        description: 'User Email Address'
        required: true
        default: 'robert.altmiller@databricks.com'
      ODCS_CONTRACT_CATALOG: # variable
        description: 'ODCS Contract Databricks Catalog'
        required: true
        default: 'hive_metastore'
      ODCS_CONTRACT_SCHEMA: # variable
        description: 'ODCS Contract Databricks Schema'
        required: true
        default: 'default'

jobs:
  deploy:
    name: Deploy Data Contract Workdflows with Databricks Asset Bundles (DABS)
    runs-on: ubuntu-latest
    env:
      DATABRICKS_CFG_PATH: "/home/runner/.databrickscfg"

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - uses: actions/setup-python@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Pip Install Requirements
        run: pip install -r requirements.txt

      - name: Setup Databricks Asset Bundles Authentication
        working-directory: .  
        run: |
          set -x
          echo "Creating $DATABRICKS_CFG_PATH"
          CONFIG_FILE=$DATABRICKS_CFG_PATH
          echo "[DEFAULT]" > "$CONFIG_FILE"
          echo "host=${{ secrets.DATABRICKS_HOST }}" >> "$CONFIG_FILE"
          echo "token=${{ secrets.DATABRICKS_TOKEN }}" >> "$CONFIG_FILE"
          cat "$CONFIG_FILE"

      - name: Setup Environment Variables
        run: |
          set -x
          # Get target environment for DABs
          TARGET="${{ github.event.inputs.ENVIRONMENT || 'dev' }}"
          echo "TARGET: $TARGET"
          
          # Get branch name
          export BRANCH_NAME="$GITHUB_REF_NAME"
          echo "BRANCH_NAME: $BRANCH_NAME"

          # Get ODCS contract catalog name
          USER_EMAIL="${{ github.event.inputs.USER_EMAIL || 'robert.altmiller@databricks.com' }}"
          echo "USER_EMAIL: $USER_EMAIL"
          
          # Get ODCS contract schema name
          ODCS_CONTRACT_CATALOG="${{ github.event.inputs.ODCS_CONTRACT_CATALOG || 'hive_metastore' }}"
          echo "ODCS_CONTRACT_CATALOG: $ODCS_CONTRACT_CATALOG"

          # Get user email, fallback if not provided via workflow input
          ODCS_CONTRACT_SCHEMA="${{ github.event.inputs.ODCS_CONTRACT_SCHEMA || 'default' }}"
          echo "ODCS_CONTRACT_SCHEMA: $ODCS_CONTRACT_SCHEMA"
      
          # Convert email to username
          USER_NAME=$(echo "$USER_EMAIL" | cut -d '@' -f 1 | tr '.' '_')
          echo "USER_NAME: $USER_NAME"
      
          # Optionally make them available to later steps
          echo "TARGET=$TARGET" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "ODCS_CONTRACT_CATALOG=$ODCS_CONTRACT_CATALOG" >> $GITHUB_ENV
          echo "ODCS_CONTRACT_SCHEMA=$ODCS_CONTRACT_SCHEMA" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV

      - name: Create Create Contracts Databricks Workflow Templates
        run: |
          python3 resources/base_parameters/inject_base_params.py

      - name: Validate and Deploy Databricks Asset Bundles
        working-directory: .  
        run: |
          set -x
          # Validate and deploy DABS
          output=$(databricks bundle validate --profile DEFAULT --target $TARGET  --var="branch_name=$BRANCH_NAME" --var="user_email=$USER_EMAIL" --var="user_name=$USER_NAME" --var="odcs_contract_catalog=$ODCS_CONTRACT_CATALOG" --var="odcs_contract_schema=$ODCS_CONTRACT_SCHEMA")
          if echo $output | grep -q "Validation OK!"; then
            echo "Databricks Bundle Deploy Validation OK = True"
            echo "Deploying Databricks Asset Bundle to Workspace"
            databricks bundle deploy --profile DEFAULT --target $TARGET --var="branch_name=$BRANCH_NAME" --var="user_email=$USER_EMAIL" --var="user_name=$USER_NAME" --var="odcs_contract_catalog=$ODCS_CONTRACT_CATALOG" --var="odcs_contract_schema=$ODCS_CONTRACT_SCHEMA"
          else
            echo "Databricks Bundle Deploy Validation OK = False"
            exit 1
          fi