name: Deploy Databricks Contracts Workflows

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ENVIRONMENT: # variable
        description: 'Deploy Environment (dev/test/prod)'
        required: true
        default: 'dev'
      USER_EMAIL: # variable
        description: 'User Email Address'
        required: true
        default: 'robert.altmiller@databricks.com'

jobs:
  deploy:
    name: Deploy Data Contracts with Databricks Asset Bundles (DABS)
    runs-on: ubuntu-latest
    
    env:
      DATABRICKS_CFG_PATH: "/home/runner/.databrickscfg"

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks

      - name: Set up .databrickscfg
        run: |
          echo "Creating $DATABRICKS_CFG_PATH"
          CONFIG_FILE=$DATABRICKS_CFG_PATH
          echo "[DEFAULT]" > "$CONFIG_FILE"
          echo "host=${{ secrets.DATABRICKS_HOST }}" >> "$CONFIG_FILE"
          echo "token=${{ secrets.DATABRICKS_TOKEN }}" >> "$CONFIG_FILE"
          cat "$CONFIG_FILE"
      
          # Get branch name
          export BRANCH_NAME="$GITHUB_REF_NAME"
          echo "BRANCH_NAME: $BRANCH_NAME"
      
          # Get user email, fallback if not provided via workflow input
          USER_EMAIL="${{ github.event.inputs.USER_EMAIL || 'robert.altmiller@databricks.com' }}"
          echo "USER_EMAIL: $USER_EMAIL"
      
          # Convert email to username
          USER_NAME=$(echo "$USER_EMAIL" | cut -d '@' -f 1 | tr '.' '_')
          echo "USER_NAME: $USER_NAME"
      
          # Optionally make them available to later steps
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          output = $(databricks bundle validate --profile DEFAULT --var="branch_name=$BRANCH_NAME" --var="user_email=$USER_EMAIL --var="user_name=$USER_NAME")

  # - name: validate-and-run-bundle
  #   run: |
  #     echo "setting up databricks authentication"
  #     mkdir -p "$HOME"
  #     CONFIG_FILE=$DATABRICKS_CFG_PATH
  #     echo "[DEFAULT]" > "$CONFIG_FILE"
  #     echo "host = ${{ secrets.DATABRICKS_HOST }}" >> "$CONFIG_FILE"
  #     echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> "$CONFIG_FILE"

  #       # echo "Creating ~/.databrickscfg"
  #       # mkdir -p "$HOME"
  #       # cat <<EOF > $DATABRICKS_CFG_PATH 
  #       # [DEFAULT]
  #       # host = ${{ secrets.DATABRICKS_HOST }}
  #       # token = ${{ secrets.DATABRICKS_TOKEN }}
  #       # EOF
  #       # mv $DATABRICKS_CFG_PATH /root/.databrickscfg


        # output = $(databricks bundle validate --profile DEFAULT --var="branch_name=$BRANCH_NAME" --var="user_email=$USER_EMAIL --var="user_name=$USER_NAME")
        # if echo $output | grep -q "Validation OK!"; then
        #   echo "Databricks Bundle Deploy Validation OK = True"
        #   echo "Deploying Databricks Asset Bundle to Workspace"
        #   databricks bundle validate --profile DEFAULT --var="branch_name=$BRANCH_NAME" --var="user_email=$USER_EMAIL" --var="user_name=$USER_NAME"
        # else
        #   echo "Databricks Bundle Deploy Validation OK = False"
        #   exit 1
        # fi